### ISSUE TITLE
Task List CRUD APIs

### ISSUE THREAD

**Issue by thisissvikas** [Vikas-Open-Source/get-it-done#3]
### Acceptance Criteria
- [ ] CRUD API Spec for Task List Resource
- [ ] Schema Design for Task List Resource
- [ ] CRUD API Implementation for Task List Resource
- [ ] Unit Testing
